{{- range $i, $ns := .Values.checkNamespaces -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.serviceAccount }}
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Values.serviceAccount }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount }}
  namespace: {{ $.Release.Namespace }}
{{ end }}
