apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-cert-exporter.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "hlf-cert-exporter.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
